version: '3.8'
services:
  spring-app:
    image: book-exchange-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - never_gona_give_you_up:/data/db
      - never_gona_let_you_down:/data/configdb
volumes:
  never_gona_give_you_up:
    driver: local
  never_gona_let_you_down:
    driver: local
