version: '3.8'
services:
  domain-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: domain-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo
      - nats
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - nats
  mongo:
    image: mongo:7.0.14
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
        - .env
    volumes:
      - db_volume:/data/db
      - config_volume:/data/configdb
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
volumes:
  db_volume:
    driver: local
  config_volume:
    driver: local
