version: '3.8'
services:
  spring-app:
    image: book-exchange-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://user:root@mongo:27017/
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_DATABASE: book_x_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - never_gona_give_you_up:/data/db
      - never_gona_let_you_down:/data/configdb
volumes:
  never_gona_give_you_up:
    driver: local
  never_gona_let_you_down:
    driver: local
