spring:
  application:
    name: BookExchangeService
  data:
    mongodb:
      uri: mongodb://user:root@localhost:27017/
      database: myDatabase
profiling:
  enabled: true
validation:
  params:
    future-years-allowance: 5
