spring:
  application:
    name: BookExchangeService
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
profiling:
  enabled: true
validation:
  params:
    future-years-allowance: 5
