apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-x
  labels:
    app: book-x-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-x-app
  template:
    metadata:
      labels:
        app: book-x-app
    spec:
      containers:
        - name: book-x-app
          image: book-exchange-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_port
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_database_name

---
apiVersion: v1
kind: Service
metadata:
  name: book-x-app-service
spec:
  selector:
    app: book-x-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
