apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/mongodb
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
