apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-app
  labels:
    app: domain-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: domain-app
  template:
    metadata:
      labels:
        app: domain-app
    spec:
      containers:
        - name: domain-app
          image: domain-service-app:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_port
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongo_database_name
            - name: NATS_CONNECTION_URI
              valueFrom:
                configMapKeyRef:
                  name: nats-configmap
                  key: nats_connection_uri
---
apiVersion: v1
kind: Service
metadata:
  name: domain-app-service
spec:
  selector:
    app: domain-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
