spring:
  application:
    name: BookExchangeService
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
profiling:
  enabled: true
validation:
  params:
    future-years-allowance: 5
mongock:
  migration-scan-package: pet.project.app.config
notification:
  buffer:
    interval: PT10S
    items-max-amount: 100
server:
  port: 8081
nats:
  connection-uri: ${NATS_CONNECTION_URI}
