spring:
  application:
    name: BookExchangeService
  data:
    mongodb:
      uri: ${MONGO_ATLAS_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    topic:
      amount-increased: ${KAFKA_AMOUNT_INCREASED_TOPIC}
    consumer:
      auto-offset-reset: latest
profiling:
  enabled: true
validation:
  params:
    future-years-allowance: 5
mongock:
  migration-scan-package: pet.project.app.config
notification:
  buffer:
    interval: PT10S
    items-max-amount: 10
server:
  port: 8081
nats:
  connection-uri: ${NATS_CONNECTION_URI}
